package com.example.moodspace;

public enum FollowCallbackId implements CallbackId {
    ADD_FOLLOWER_SUCCESS,
    ADD_FOLLOWER_COMPLETE,
    ADD_USER_FOLLOWING_FAIL,
    ADD_USER_AS_FOLLOWER_FAIL,

    REMOVE_FOLLOWER_SUCCESS,
    REMOVE_FOLLOWER_FAIL,
    SEND_REQUEST_SUCCESS,
    SEND_REQUEST_FAIL,
    REMOVE_REQUEST_SUCCESS,
    REMOVE_REQUEST_FAIL,
    FOLLOWEE_MOOD_READ_FAIL,
}
