package com.example.moodspace;

public enum FollowCallbackId implements CallbackId {
    ADD_FOLLOWER_COMPLETE,
    ADD_USER_TO_FOLLOWING_FAIL,
    ADD_USER_AS_FOLLOWER_FAIL,

    REMOVE_FOLLOWER_COMPLETE,
    REMOVE_FROM_FOLLOWING_FAIL,
    REMOVE_AS_FOLLOWER_FAIL,

    ADD_FOLLOW_REQUEST_COMPLETE,
    ADD_FOLLOW_REQUEST_TO_FAIL,
    ADD_FOLLOW_REQUEST_FROM_FAIL,

    REMOVE_FOLLOW_REQUEST_COMPLETE,
    REMOVE_FOLLOW_REQUEST_TO_FAIL,
    REMOVE_FOLLOW_REQUEST_FROM_FAIL,

    ACCEPT_FOLLOW_REQUEST_COMPLETE,
    FOLLOWEE_MOOD_READ_FAIL,
}
